/**
 * JSON Schema → TypeScript code generator.
 *
 * Walks the schema as a structural tree. NO REGEX anywhere — every
 * decision is made on object shape and discriminator fields the
 * spec defines (`type`, `properties`, `items`, `enum`, `oneOf`, etc.).
 *
 * Scope: the subset of JSON Schema actually emitted by MCP tool
 * definitions in practice:
 *
 *   - `{ type: "object", properties: {…}, required: [], additionalProperties }`
 *   - `{ type: "array", items: {…} }`
 *   - `{ type: "string" | "number" | "integer" | "boolean" | "null" }`
 *   - `{ enum: [...] }`
 *   - `{ oneOf: [...] }`, `{ anyOf: [...] }`
 *   - `{ const: <value> }`
 *
 * Unknown / unsupported shapes degrade to `unknown` — never throws,
 * never emits invalid TS.
 *
 * The output is pretty-printed with two-space indentation. Names are
 * sanitized to valid TS identifiers via a char-code walk (no regex).
 *
 * Reserved names (`default`, `function`, etc.) are quoted as string
 * properties. Optional fields end with `?`.
 */

export interface JsonSchemaLike {
  type?: string;
  properties?: Record<string, JsonSchemaLike>;
  required?: string[];
  additionalProperties?: boolean | JsonSchemaLike;
  items?: JsonSchemaLike | JsonSchemaLike[];
  enum?: unknown[];
  const?: unknown;
  oneOf?: JsonSchemaLike[];
  anyOf?: JsonSchemaLike[];
  description?: string;
  format?: string;
}

export interface McpToolDef {
  name: string;
  description?: string;
  inputSchema: JsonSchemaLike;
  /**
   * Output shape, when the tool publishes one. Optional in MCP today;
   * code-mode emits the return type as `unknown` when missing.
   */
  outputSchema?: JsonSchemaLike;
}

export interface ToolApiSpec {
  /** Emitted module text. */
  code: string;
  /** Names of the emitted method properties (sanitized). */
  methodNames: string[];
  /** Map from sanitized method name → original MCP tool name. */
  nameMap: Record<string, string>;
}

export interface GenerateApiOptions {
  /** Identifier for the generated module's `Toolbox` interface. Default "Toolbox". */
  toolboxName: string;
  /** Header banner placed at the top of the emitted file. */
  banner: string;
}

const DEFAULT_OPTIONS: GenerateApiOptions = {
  toolboxName: "Toolbox",
  banner: "// AUTO-GENERATED by @prune/code-mode-mcp. Do not edit by hand.",
};

/**
 * Generate a typed-API TypeScript module from a set of MCP tool
 * definitions. The output exports a single interface named
 * `Toolbox` (configurable). Each method's parameter type is the
 * inline TS shape derived from `inputSchema`; return type is the
 * shape derived from `outputSchema` or `unknown`.
 */
export function generateToolboxApi(
  tools: ReadonlyArray<McpToolDef>,
  options: Partial<GenerateApiOptions> = {}
): ToolApiSpec {
  // Field-by-field merge — a passed-through `undefined` must not
  // shadow the default. Plain spread would let `{ toolboxName: undefined }`
  // win and emit `export interface undefined { ... }`.
  const opts: GenerateApiOptions = {
    toolboxName:
      typeof options.toolboxName === "string" && options.toolboxName.length > 0
        ? options.toolboxName
        : DEFAULT_OPTIONS.toolboxName,
    banner:
      typeof options.banner === "string"
        ? options.banner
        : DEFAULT_OPTIONS.banner,
  };
  const lines: string[] = [];
  const methodNames: string[] = [];
  const nameMap: Record<string, string> = {};

  lines.push(opts.banner);
  lines.push("");
  lines.push(`export interface ${opts.toolboxName} {`);

  const usedNames = new Set<string>();
  for (const tool of tools) {
    if (!tool || typeof tool.name !== "string" || tool.name.length === 0) {
      continue;
    }
    const sanitized = sanitizeIdentifier(tool.name);
    const unique = uniquify(sanitized, usedNames);
    usedNames.add(unique);
    methodNames.push(unique);
    nameMap[unique] = tool.name;

    if (typeof tool.description === "string" && tool.description.length > 0) {
      lines.push(`  /** ${escapeJsDoc(tool.description)} */`);
    }
    const paramsTs = renderSchemaInline(tool.inputSchema, 2);
    const returnTs = tool.outputSchema
      ? renderSchemaInline(tool.outputSchema, 2)
      : "unknown";
    lines.push(`  ${unique}(params: ${paramsTs}): Promise<${returnTs}>;`);
  }

  lines.push("}");
  lines.push("");

  return {
    code: lines.join("\n"),
    methodNames,
    nameMap,
  };
}

/* ------------------------------------------------------------------ */
/* Schema → TS shape                                                  */
/* ------------------------------------------------------------------ */

function renderSchemaInline(
  schema: JsonSchemaLike | undefined,
  indent: number
): string {
  if (!schema || typeof schema !== "object") return "unknown";

  if (schema.const !== undefined) return renderLiteral(schema.const);

  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return schema.enum.map(renderLiteral).join(" | ");
  }

  if (Array.isArray(schema.oneOf) && schema.oneOf.length > 0) {
    return schema.oneOf.map((s) => renderSchemaInline(s, indent)).join(" | ");
  }
  if (Array.isArray(schema.anyOf) && schema.anyOf.length > 0) {
    return schema.anyOf.map((s) => renderSchemaInline(s, indent)).join(" | ");
  }

  if (typeof schema.type === "string") {
    switch (schema.type) {
      case "string":
        return "string";
      case "number":
      case "integer":
        return "number";
      case "boolean":
        return "boolean";
      case "null":
        return "null";
      case "array": {
        if (Array.isArray(schema.items)) {
          // tuple
          const items = schema.items.map((s) => renderSchemaInline(s, indent));
          return `[${items.join(", ")}]`;
        }
        const inner = renderSchemaInline(schema.items as JsonSchemaLike | undefined, indent);
        return `Array<${inner}>`;
      }
      case "object":
        return renderObjectShape(schema, indent);
    }
  }

  // No discriminator at all — best we can do is fall through to object
  // when properties are present.
  if (schema.properties) return renderObjectShape(schema, indent);

  return "unknown";
}

function renderObjectShape(schema: JsonSchemaLike, indent: number): string {
  const props = schema.properties ?? {};
  const required = new Set(
    Array.isArray(schema.required) ? schema.required.filter((s) => typeof s === "string") : []
  );

  const propKeys = Object.keys(props);
  if (propKeys.length === 0) {
    if (schema.additionalProperties === false) return "Record<string, never>";
    if (
      typeof schema.additionalProperties === "object" &&
      schema.additionalProperties !== null
    ) {
      const inner = renderSchemaInline(
        schema.additionalProperties as JsonSchemaLike,
        indent + 2
      );
      return `Record<string, ${inner}>`;
    }
    return "Record<string, unknown>";
  }

  const pad = " ".repeat(indent + 2);
  const closingPad = " ".repeat(indent);
  const lines: string[] = ["{"];
  for (const key of propKeys) {
    const subSchema = props[key]!;
    const optional = required.has(key) ? "" : "?";
    const safeKey = isSafeIdentifier(key) ? key : JSON.stringify(key);
    const description =
      typeof subSchema.description === "string" && subSchema.description.length > 0
        ? subSchema.description
        : null;
    if (description) {
      lines.push(`${pad}/** ${escapeJsDoc(description)} */`);
    }
    const rendered = renderSchemaInline(subSchema, indent + 2);
    lines.push(`${pad}${safeKey}${optional}: ${rendered};`);
  }
  if (
    typeof schema.additionalProperties === "object" &&
    schema.additionalProperties !== null
  ) {
    const inner = renderSchemaInline(
      schema.additionalProperties as JsonSchemaLike,
      indent + 2
    );
    lines.push(`${pad}[k: string]: ${inner};`);
  }
  lines.push(`${closingPad}}`);
  return lines.join("\n");
}

function renderLiteral(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return "unknown";
}

/* ------------------------------------------------------------------ */
/* Identifier sanitization (no regex)                                 */
/* ------------------------------------------------------------------ */

/**
 * TypeScript reserved words and contextual reserved words that
 * commonly collide. Listed here so we can quote rather than fail.
 */
const RESERVED_NAMES = new Set<string>([
  "default", "function", "class", "enum", "interface", "type", "const",
  "let", "var", "return", "if", "else", "while", "for", "do", "switch",
  "case", "break", "continue", "import", "export", "new", "this",
  "super", "throw", "try", "catch", "finally", "delete", "in", "of",
  "instanceof", "typeof", "void", "yield", "await", "async", "static",
  "public", "private", "protected", "readonly", "abstract", "true",
  "false", "null", "undefined",
]);

/**
 * Convert an MCP tool name to a valid TS identifier. Walks code
 * points: keeps [A-Za-z0-9_$], replaces anything else with '_'. If
 * the first character isn't a valid identifier-start, prefix with '_'.
 */
export function sanitizeIdentifier(raw: string): string {
  if (typeof raw !== "string" || raw.length === 0) return "_tool";
  let out = "";
  for (let i = 0; i < raw.length; i++) {
    const c = raw.charCodeAt(i);
    const isUpper = c >= 65 && c <= 90;
    const isLower = c >= 97 && c <= 122;
    const isDigit = c >= 48 && c <= 57;
    const isUnderscore = c === 95;
    const isDollar = c === 36;
    if (isUpper || isLower || isUnderscore || isDollar) {
      out += raw[i];
    } else if (isDigit) {
      if (out.length === 0) out += "_";
      out += raw[i];
    } else {
      out += "_";
    }
  }
  if (out.length === 0) return "_tool";
  if (RESERVED_NAMES.has(out)) return `_${out}`;
  return out;
}

function uniquify(name: string, taken: Set<string>): string {
  if (!taken.has(name)) return name;
  let i = 2;
  while (taken.has(`${name}_${i}`)) i++;
  return `${name}_${i}`;
}

function isSafeIdentifier(name: string): boolean {
  if (typeof name !== "string" || name.length === 0) return false;
  const c0 = name.charCodeAt(0);
  const startOk =
    (c0 >= 65 && c0 <= 90) ||
    (c0 >= 97 && c0 <= 122) ||
    c0 === 95 ||
    c0 === 36;
  if (!startOk) return false;
  for (let i = 1; i < name.length; i++) {
    const c = name.charCodeAt(i);
    const ok =
      (c >= 65 && c <= 90) ||
      (c >= 97 && c <= 122) ||
      (c >= 48 && c <= 57) ||
      c === 95 ||
      c === 36;
    if (!ok) return false;
  }
  return !RESERVED_NAMES.has(name);
}

function escapeJsDoc(text: string): string {
  // The only sequence that can close a JSDoc is `*/`. Replace it
  // structurally — no regex.
  let out = "";
  for (let i = 0; i < text.length; i++) {
    if (text[i] === "*" && text[i + 1] === "/") {
      out += "* /";
      i += 1;
    } else if (text.charCodeAt(i) === 0x0a) {
      out += " ";
    } else {
      out += text[i];
    }
  }
  return out;
}
